In [4]:
import pandas as pd
import json

# df = pd.read_csv("cleaned_data.csv")
# df = df[['id', 'type of property', 'Sub-type', 'City', 'Province', 'Region', 'post code', 'Price', 'Median price PC', 'Garden', 'Terrace','Living area','Bedrooms','Surface of the plot','Garden surface','Swimming pool','Open fire','Terrace surface','Number of frontages','Building condition', 'Kitchen type']]
df= pd.read_csv('coef.csv')
df.head()

,Unnamed: 0,id,type of property,Sub-type,City,Province,Region,post code,Price,Median price PC,...,Living area,Bedrooms,Surface of the plot,Garden surface,Swimming pool,Open fire,Terrace surface,Number of frontages,Building condition,Kitchen type
0,0,10092563,APARTMENT,apartment,Antwerpen,Antwerp,Flanders,2000,485000.0,1.563855,...,0.506654,0.391822,0.00000,0.0,0.0,0.0,0.306666,0.086023,0.270630,0.247186
1,1,10092564,APARTMENT,duplex,Antwerpen,Antwerp,Flanders,2000,455000.0,1.563855,...,0.533320,0.391822,0.00000,0.0,0.0,0.0,0.245333,0.057349,0.270630,0.247186
2,2,10092568,HOUSE,house,Vitrival,Namur,Wallonia,5070,155000.0,0.733578,...,0.238207,0.384598,0.07136,0.0,0.0,0.0,0.588615,0.143936,0.111288,0.223927
3,3,10092576,APARTMENT,apartment,Liedekerke,Flemish Brabant,Flanders,1770,195000.0,1.087026,...,0.479988,0.391822,0.00000,0.0,0.0,0.0,0.163555,0.057349,0.180420,0.082395
4,4,10092579,APARTMENT,duplex,Wilrijk,Antwerp,Flanders,2610,395000.0,0.883628,...,0.671983,0.587733,0.00000,0.0,0.0,0.0,0.449777,0.057349,0.270630,0.247186

In [7]:
prop_type_list = ['APARTMENT','HOUSE','OTHERS']
# corr_list_of_list = []
corr_dict = {}

for i in prop_type_list:
    corr = df[df['type of property'] == i].corr()
    corr_list = dict(corr['Price'])
    # corr_list_of_list.append(corr_list)
    corr_dict[i] = corr_list


with open("correlations.json", "w") as outfile:
    json.dump(corr_dict, outfile, indent=4)

{'APARTMENT': {'id': -0.004372297225743739,
  'post code': -0.008965095597175381,
  'Price': 1.0,
  'Median price PC': 0.5147649514268057,
  'Garden': 0.034863904016828234,
  'Terrace': 0.1324804687994953,
  'Living area': 0.5066562670466416,
  'Bedrooms': 0.3920082475153873,
  'Surface of the plot': nan,
  'Garden surface': 0.05175518794131327,
  'Swimming pool': 0.031078221700851238,
  'Open fire': 0.11325038678957569,
  'Terrace surface': 0.3069788640303025,
  'Number of frontages': 0.05735668274467199,
  'Building condition': 0.18044190535763563,
  'Kitchen type': 0.16469305892584665},
 'HOUSE': {'id': 0.0356097393050197,
  'post code': -0.15983436484684393,
  'Price': 1.0,
  'Median price PC': 0.5041530580772475,
  'Garden': 0.06369652856017873,
  'Terrace': 0.12197121717840823,
  'Living area': 0.5209731037711804,
  'Bedrooms': 0.38471912160168736,
  'Surface of the plot': 0.35663510533696324,
  'Garden surface': 0.13921932905397283,
  'Swimming pool': 0.30602618204075605,
  'Open fire': 0.153917653033404,
  'Terrace surface': 0.12598649380298219,
  'Number of frontages': 0.21581375468710776,
  'Building condition': 0.2224875570689933,
  'Kitchen type': 0.22364121240118326},
 'OTHERS': {'id': 0.08237733275153382,
  'post code': -0.21994039569480753,
  'Price': 1.0,
  'Median price PC': 0.31082535725133165,
  'Garden': -0.008342787812018436,
  'Terrace': 0.1161339159094571,
  'Living area': 0.5998241945136685,
  'Bedrooms': 0.57836701675908,
  'Surface of the plot': 0.35206358161868456,
  'Garden surface': 0.1517222920777935,
  'Swimming pool': 0.2723950443954285,
  'Open fire': 0.11899583845091953,
  'Terrace surface': 0.18462881157834368,
  'Number of frontages': 0.255489139781611,
  'Building condition': 0.2849722705185927,
  'Kitchen type': 0.21007454362753547}}

In [9]:
national_median = df['Price'].median()

pc_coefs = dict(zip(df['post code'], df['Median price PC']/national_median))

with open("pc_coefs.json", "w") as outfile:
    json.dump(pc_coefs, outfile, indent=4)

In [17]:
num_col_list = ['Living area','Bedrooms','Surface of the plot','Garden surface','Terrace surface','Number of frontages','Building condition', 'Kitchen type']
prop_type_list = ['APARTMENT','HOUSE','OTHERS']
median_dict = {}

for i in prop_type_list:
    dict1 = {}
    for j in num_col_list:
        prop_type_mean = df[(df['type of property']== i) & (df[j] != 0) ][j].median()
        # df.loc[(df['type of property'] == i ), j] = df[j]/prop_type_mean
        dict1[j] = prop_type_mean
    median_dict[i] = dict1

with open("medians.json", "w") as outfile:
    json.dump(median_dict, outfile, indent=4)

In [2]:
import requests
import json

url = 'http://127.0.0.1:8000/predict'

with open('input_data.json') as json_file1:
    input_data = json.load(json_file1)


x = requests.post(url, json = input_data)

print(x.text)

{"prediction":441951.74045767664,"status_code":201}